name: Test Action Send Mail action
on: workflow_dispatch

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        include:
          - subject: Plain body (attachment)
            attachments: main.go
            body: |
              first line
              second line
          - subject: HTML body (attachments)
            attachments: package.json
            html_body: |
              <!DOCTYPE html>
              <html>
              <body>
              <h1>Heading</h1>
              <p>Paragraph</p>
              </body>
              </html>
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Send mail
        uses: step-security/action-send-mail@c6939fdbd31541bf2930ccff7765b838320e23da # release
        with:
          server_address: ${{secrets.ADDRESS}}
          server_port: 465
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          subject: ${{matrix.subject}}
          body: ${{matrix.body}}
          html_body: ${{matrix.html_body}}
          to: shubhammalik309@gmail.com
          from: github-actions
          attachments: ${{matrix.attachments}}
          convert_markdown: ${{matrix.convert_markdown}}
          priority: high

  url-test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Send mail
        uses: step-security/action-send-mail@c6939fdbd31541bf2930ccff7765b838320e23da # release
        with:
          connection_url: smtp+starttls://${{secrets.USERNAME}}:${{secrets.PASSWORD}}@${{secrets.ADDRESS}}/
          subject: Plain body with connection_url
          body: |
            first line
            second line
          to: shubhammalik309@gmail.com
          from: github-actions
